package com.microworld.ems.eventservice.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.Date;

@DynamoDBTable(tableName = "EventInfo")
public class EventsTable {

    private String eventId;
    private Date startDate;
    private Date endDate;
    private String eventHolderEmail;
    private long zipCode;
    private String eventType;

//    public EventsTable(String eventId, Date startDate, Date endDate, String eventHolderEmail, long zipCode, String eventType) {
//        this.eventId = eventId;
//        this.startDate = startDate;
//        this.endDate = endDate;
//        this.eventHolderEmail = eventHolderEmail;
//        this.zipCode = zipCode;
//        this.eventType = eventType;
//    }

    public EventsTable() {

    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getEventId() {
        return eventId;
    }

    public void setEventId(String eventId) {
        this.eventId = eventId;
    }

    @DynamoDBAttribute
    public Date getStartDate() {
        return startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @DynamoDBAttribute
    public Date getEndDate() {
        return endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    @DynamoDBAttribute
    public String getEventHolderEmail() {
        return eventHolderEmail;
    }

    public void setEventHolderEmail(String eventHolderEmail) {
        this.eventHolderEmail = eventHolderEmail;
    }

    @DynamoDBAttribute
    public long getZipCode() {
        return zipCode;
    }

    public void setZipCode(long zipCode) {
        this.zipCode = zipCode;
    }

    @DynamoDBAttribute
    public String getEventType() {
        return eventType;
    }

    public void setEventType(String eventType) {
        this.eventType = eventType;
    }


    @Override
    public String toString() {
        return "EventsTable{" +
                "eventId='" + eventId + '\'' +
                ", startDate=" + startDate +
                ", endDate=" + endDate +
                ", eventHolderEmail='" + eventHolderEmail + '\'' +
                ", zipCode=" + zipCode +
                ", eventType='" + eventType + '\'' +
                '}';
    }
}
